### ISSUE TITLE
Wrong exit code with '--specs' parameter

### ISSUE THREAD

**Issue by stophi-dev** [collaborationFactory/cplace-npm-tools#55]
When running `cplace-cli` with the `--specs` parameter, the program will show an error and exit with exit code '1' although all tests that are met by the filter have passed.

Example:
`cplace-cli e2e --specs '**/login.spec.ts' && echo 'It works correctly if we see this text'`

Output:
> [...]
> One of the E2E Tests in plugin cf.cplace.training.extended has failed
> Could not execute given command:
>         One of the E2E Tests has failed

This is especially problematic on continous integration environments. It would mark the tests as failed, although all tests passed.

**Comment by stefancplace** [comment]
Hi @stophi-dev 
I had a look into this issue. This is basically about cplace-cli trying to execute tests specified in --specs in a cplace plugin that doesnt contain the specified test.
I dont think this is a bug any more and can be fixed by specifying the plugin that contains the specified test e.g.:
`cplace-cli e2e --specs '**/login.spec.ts' --plugins cf.cplace.platform && echo 'It works correctly if we see this text'`

**Comment by stefancplace** [comment]
@stophi-dev  is there any news ? can we close the issue?

**Comment by stophi-dev** [comment]
I'd like to run this spec pattern on _all_ plugins. This is actually what it is doing, only the return code is not what I would expect.
